language: node_js
node_js:
  - "6.9.4"
before_install: npm install -g grunt-cli
before_script:
  - grunt compile
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - grunt publish
